import * as THREE from 'three';
import { TEAMS } from '../data/teams.js';
import { STADIUMS } from '../data/stadiums.js';
import { PLAYS } from '../data/plays.js';
import { FIELD, ROLES, SETTINGS_DEFAULTS } from '../../../shared/constants.js';
import { createMatchState, applyPlayResult, displayYardLine, ordinal } from '../football/FootballRules.js';

export class Game {
  constructor({ canvas, uiRoot, toastRoot }) {
    this.canvas = canvas; this.uiRoot = uiRoot; this.toastRoot = toastRoot;
    this.renderer = new THREE.WebGLRenderer({ canvas, antialias: false, powerPreference: 'high-performance' });
    this.scene = new THREE.Scene(); this.camera = new THREE.PerspectiveCamera(55, 1, 0.1, 500);
    this.keys = new Set(); this.players = []; this.settings = loadSettings(); this.mode = 'exhibition';
    this.homeId = localStorage.getItem('gb97-home') || TEAMS[0].id; this.awayId = localStorage.getItem('gb97-away') || TEAMS[1].id; this.stadiumId = localStorage.getItem('gb97-stadium') || STADIUMS[0].id;
    this.playIndex = 0; this.currentPlay = PLAYS[0]; this.target = 'WR1'; this.phase = 'menu'; this.status = 'Pick a mode.'; this.last = performance.now(); this.elapsed = 0; this.audio = null;
  }
  start() { this.resize(); addEventListener('resize', () => this.resize()); addEventListener('keydown', (e) => this.onKey(e)); addEventListener('keyup', (e) => this.keys.delete(e.code)); this.uiRoot.addEventListener('click', (e) => this.onClick(e)); this.showMenu(); this.loop(); }
  resize() { this.renderer.setSize(innerWidth, innerHeight, false); this.renderer.setPixelRatio(Math.min(devicePixelRatio, 1.25)); this.camera.aspect = innerWidth / innerHeight; this.camera.updateProjectionMatrix(); }
  onClick(e) { const b = e.target.closest('button'); if (!b) return; this.sound('select'); const a = b.dataset.action; if (a === 'exhibition') { this.mode = 'exhibition'; this.showTeams(); } if (a === 'practice') { this.mode = 'practice'; this.showTeams(); } if (a === 'settings') this.showSettings(); if (a === 'patch') this.showPatch(); if (a === 'credits') this.toast('Original fictional arcade football prototype.'); if (a === 'main-menu') this.showMenu(); if (a === 'continue-stadium') this.showStadiums(); if (a === 'random-cpu') { const pool = TEAMS.filter(t => t.id !== this.homeId); this.awayId = pool[Math.floor(Math.random() * pool.length)].id; localStorage.setItem('gb97-away', this.awayId); this.showTeams(); } if (a === 'start-game') this.startMatch(); if (a === 'rematch') this.startMatch(); if (b.dataset.team) { if (b.dataset.cpu === '1') this.awayId = b.dataset.team; else this.homeId = b.dataset.team; localStorage.setItem('gb97-home', this.homeId); localStorage.setItem('gb97-away', this.awayId); this.showTeams(); } if (b.dataset.stadium) { this.stadiumId = b.dataset.stadium; localStorage.setItem('gb97-stadium', this.stadiumId); this.showStadiums(); } if (b.dataset.play) this.callPlay(PLAYS.find(p => p.id === b.dataset.play)); }
  onKey(e) { this.keys.add(e.code); if (this.phase === 'play-select') { if (e.code === 'ArrowLeft' || e.code === 'KeyA') this.playIndex = (this.playIndex + PLAYS.length - 1) % PLAYS.length; if (e.code === 'ArrowRight' || e.code === 'KeyD') this.playIndex = (this.playIndex + 1) % PLAYS.length; if (e.code === 'Enter' || e.code === 'Space') this.callPlay(PLAYS[this.playIndex]); } else if (this.phase === 'pre-snap' && e.code === 'Space') this.snap(); else if (this.phase === 'live' && ['Digit1','Digit2','Digit3','Digit4'].includes(e.code)) this.throwPass(['WR1','WR2','TE','RB'][Number(e.code.slice(5)) - 1]); if (e.code === 'Escape') this.showMenu(); }
  showMenu() { this.phase = 'menu'; this.uiRoot.innerHTML = `<section class="screen menu-screen"><div><p class="eyebrow">v0.1.0 PS1 Arcade Football Prototype</p><h1>GRIDIRON BLITZ 97</h1><p class="subtitle">7-on-7 fictional football under blocky lights.</p></div><nav class="menu-actions"><button data-action="exhibition">Exhibition</button><button data-action="practice">Practice</button><button data-action="settings">Settings</button><button data-action="patch">Patch Notes</button><button data-action="credits">Credits</button></nav></section>`; }
  showTeams() { this.phase = 'team-select'; this.uiRoot.innerHTML = `<section class="screen select-screen"><h2>Team Select</h2><div class="select-columns"><div><h3>Player Team</h3>${TEAMS.map(t => teamCard(t, t.id === this.homeId, false)).join('')}</div><div><h3>CPU Team</h3>${TEAMS.map(t => teamCard(t, t.id === this.awayId, true)).join('')}</div></div><div class="row-actions"><button data-action="random-cpu">Random CPU</button><button data-action="continue-stadium">Continue</button><button data-action="main-menu">Back</button></div></section>`; }
  showStadiums() { this.phase = 'stadium-select'; this.uiRoot.innerHTML = `<section class="screen select-screen"><h2>Stadium Select</h2><div class="stadium-grid">${STADIUMS.map(s => `<button class="stadium-card ${s.id === this.stadiumId ? 'selected' : ''}" data-stadium="${s.id}" style="--sky:${s.sky};--wall:${s.wall};--light:${s.light}"><span class="stadium-preview"></span><strong>${s.name}</strong><small>${s.vibe}</small></button>`).join('')}</div><div class="row-actions"><button data-action="start-game">Kick Off</button><button data-action="main-menu">Main Menu</button></div></section>`; }
  showSettings() { this.uiRoot.innerHTML = `<section class="screen compact-screen"><h2>Settings</h2><p>Master, crowd, SFX, camera, quality, scanlines, and screen shake are saved locally.</p><button data-action="main-menu">Back</button></section>`; }
  showPatch() { this.uiRoot.innerHTML = `<section class="screen compact-screen"><h2>Patch Notes</h2><h3>v0.1.0 - PS1 Arcade Football Prototype</h3><ul><li>Added four fictional teams and stadiums.</li><li>Added 7-on-7 arcade football, play selection, passing, running, tackling, downs, touchdowns, scoring, AI, low-poly visuals, generated audio, and local play support.</li></ul><button data-action="main-menu">Back</button></section>`; }
  startMatch() { const homeTeam = TEAMS.find(t => t.id === this.homeId); const awayTeam = TEAMS.find(t => t.id === this.awayId); const stadium = STADIUMS.find(s => s.id === this.stadiumId); this.match = createMatchState({ homeTeam, awayTeam, stadium, mode: this.mode }); this.buildScene(stadium); this.lineup(); this.phase = 'play-select'; this.status = this.mode === 'practice' ? 'Practice field loaded.' : 'Exhibition kickoff.'; this.ensureAudio(); this.renderHud(); }
  buildScene(stadium) { this.scene.clear(); this.scene.background = new THREE.Color(stadium.sky); this.scene.fog = new THREE.Fog(stadium.sky, 85, 170); this.scene.add(new THREE.HemisphereLight('#dbeafe', '#172554', 1.6)); const sun = new THREE.DirectionalLight('#fff', 1.3); sun.position.set(20, 60, 20); this.scene.add(sun); this.field = new THREE.Group(); this.scene.add(this.field); const turf = box(FIELD.width, .2, 120, stadium.turf); turf.position.z = 50; this.field.add(turf); for (let z = 0; z <= 100; z += 5) { const l = box(FIELD.width, .05, z % 10 ? .16 : .32, '#e8efe7'); l.position.set(0,.2,z); this.field.add(l); } this.los = box(FIELD.width + 1, .08, .42, '#46d9ff'); this.first = box(FIELD.width + 1, .08, .42, '#ffd84a'); this.field.add(this.los, this.first); for (const x of [-43,43]) { const stands = box(100,8,12,stadium.wall); stands.position.set(x,4,50); this.scene.add(stands); } this.ballMesh = new THREE.Mesh(new THREE.SphereGeometry(.55,10,6), mat('#7a3d1c')); this.ballMesh.scale.set(.7,.45,1.25); this.scene.add(this.ballMesh); }
  lineup() { this.players.forEach(p => this.scene.remove(p.mesh)); this.players = []; this.offense = this.match.possession; this.dir = this.offense === 'home' ? 1 : -1; this.snapZ = this.dir === 1 ? this.match.yardLine : 100 - this.match.yardLine; const ot = this.offense === 'home' ? this.match.homeTeam : this.match.awayTeam; const dt = this.offense === 'home' ? this.match.awayTeam : this.match.homeTeam; ROLES.offense.forEach(r => this.addPlayer(r,this.offense,ot,true)); ROLES.defense.forEach(r => this.addPlayer(r,this.offense === 'home' ? 'away' : 'home',dt,false)); this.carrier = this.players.find(p => p.role === 'QB' && p.side === this.offense); this.ballMode = 'held'; this.target = this.currentPlay.recommendedTarget || 'WR1'; this.passDone = false; this.updateMarkers(); }
  addPlayer(role, side, team, off) { const pos = { QB:[0,-5], RB:[-4,-8], WR1:[-18,0], WR2:[18,0], TE:[7,-1], OL1:[-2,-1], OL2:[2,-1], DL1:[-3,3], DL2:[3,3], LB:[0,8], CB1:[-18,7], CB2:[18,7], S1:[-9,16], S2:[9,16] }[role]; const mesh = playerMesh(team, off ? team.colors.primary : team.colors.away); mesh.position.set(pos[0],0,this.snapZ + this.dir * pos[1]); this.scene.add(mesh); this.players.push({ role, side, team, mesh, route: [], routeIndex: 0, off }); }
  callPlay(play) { this.currentPlay = play; this.playIndex = PLAYS.indexOf(play); this.target = play.recommendedTarget || 'WR1'; for (const p of this.players.filter(p => p.side === this.offense)) { p.route = (play.routes[p.role] || []).map(([x,y]) => ({ x, z: this.snapZ + this.dir * y })); p.routeIndex = 0; } this.phase = 'pre-snap'; this.status = `${play.name} called. Space snaps the ball.`; this.renderHud(); }
  snap() { this.phase = 'live'; this.status = 'Ball snapped!'; this.sound('snap'); if (this.currentPlay.type === 'run') this.carrier = this.players.find(p => p.role === 'RB' && p.side === this.offense); this.renderHud(); }
  throwPass(role) { if (!this.carrier || this.carrier.role !== 'QB' || this.ballMode === 'air') return; const target = this.players.find(p => p.role === role && p.side === this.offense); if (!target) return; this.ballMode = 'air'; this.passTarget = target; this.passT = 0; this.passStart = this.carrier.mesh.position.clone(); this.passEnd = target.mesh.position.clone().add(new THREE.Vector3(0,1.5,this.dir * 7)); this.status = `Pass to ${role}!`; this.sound('throw'); }
  update(dt, time) { if (!this.match || !['live','result','play-select','pre-snap'].includes(this.phase)) return; if (this.phase === 'live') { this.updatePlayers(dt); if (this.ballMode === 'air') this.updatePass(dt); const tackler = this.players.find(p => p.side !== this.offense && this.carrier && p.mesh.position.distanceTo(this.carrier.mesh.position) < 2.25); if (tackler) this.endPlay({ type:'tackle', yards: Math.round((this.carrier.mesh.position.z - this.snapZ) * this.dir), pass: this.passDone, message: `${tackler.role} tackle!` }); if (this.carrier && (this.dir === 1 ? this.carrier.mesh.position.z >= 100 : this.carrier.mesh.position.z <= 0)) this.endPlay({ type:'touchdown', yards: 100, pass: this.passDone }); } if (this.carrier && this.ballMode === 'held') this.ballMesh.position.set(this.carrier.mesh.position.x + .35,2.4,this.carrier.mesh.position.z + .2); this.cameraUpdate(dt); }
  updatePlayers(dt) { const c = this.carrier; if (c && this.offense === 'home') { const vx = (this.keys.has('KeyD') ? 1 : 0) - (this.keys.has('KeyA') ? 1 : 0); const vz = (this.keys.has('KeyW') ? 1 : 0) - (this.keys.has('KeyS') ? 1 : 0); const len = Math.hypot(vx,vz) || 1; const sp = 15 + c.team.stats.speed * .6 + (this.keys.has('ShiftLeft') ? 6 : 0); c.mesh.position.x = clamp(c.mesh.position.x + vx / len * sp * dt, -26, 26); c.mesh.position.z = clamp(c.mesh.position.z + vz / len * sp * dt * this.dir, 0, 100); }
    for (const p of this.players) { if (p.side === this.offense && p !== c && p.route.length) moveToward(p, p.route[p.routeIndex], 10 + p.team.stats.speed * .45, dt); if (p.side !== this.offense && c) moveToward(p, c.mesh.position, 9 + p.team.stats.defense * .55, dt); p.mesh.position.y = Math.sin(this.elapsed * 12 + p.mesh.position.x) * .05; }
  }
  updatePass(dt) { this.passT += dt / .75; const t = Math.min(1, this.passT); this.ballMesh.position.lerpVectors(this.passStart, this.passEnd, t); this.ballMesh.position.y += Math.sin(t * Math.PI) * 8; this.ballMesh.rotation.x += dt * 12; if (t >= 1) { const defender = this.players.find(p => p.side !== this.offense && p.mesh.position.distanceTo(this.ballMesh.position) < 3.2); if (defender && Math.random() < .35) { this.carrier = defender; this.ballMode = 'held'; this.endPlay({ type:'interception', yards: Math.round((defender.mesh.position.z - this.snapZ) * this.dir), pass:true }); } else if (this.passTarget.mesh.position.distanceTo(this.ballMesh.position) < 5 || Math.random() < .65) { this.carrier = this.passTarget; this.ballMode = 'held'; this.passDone = true; this.status = `${this.passTarget.role} catch!`; this.sound('catch'); } else this.endPlay({ type:'incomplete', yards:0, pass:true, message:'Incomplete pass.' }); } }
  endPlay(result) { if (this.phase !== 'live') return; this.phase = 'result'; applyPlayResult(this.match, result); this.status = result.message || this.match.history[0]?.message || `${result.yards} yards.`; this.sound(result.type === 'touchdown' ? 'touchdown' : result.type === 'interception' ? 'turnover' : 'tackle'); this.renderHud(); setTimeout(() => { if (this.match.winner) this.showResults(); else { this.phase = 'play-select'; this.lineup(); this.renderHud(); if (this.match.possession === 'away') setTimeout(() => { this.callPlay(PLAYS[Math.floor(Math.random()*PLAYS.length)]); setTimeout(() => this.snap(), 700); }, 900); } }, 1300); }
  updateMarkers() { this.los.position.set(0,.35,this.snapZ); this.first.position.set(0,.38,this.snapZ + this.dir * this.match.toGo); }
  cameraUpdate(dt) { const focus = this.carrier?.mesh.position || this.ballMesh.position; const target = new THREE.Vector3(focus.x*.35,32,focus.z - this.dir*22); if (this.phase !== 'live') target.set(0,38,this.snapZ - this.dir*29); this.camera.position.lerp(target, 1 - Math.pow(.001, dt)); this.camera.lookAt(focus.x*.25,1.5,focus.z + this.dir*8); this.updateMarkers(); }
  renderHud() { if (!this.match) return; const h = this.match.homeTeam.shortName, a = this.match.awayTeam.shortName; let html = `<div class="hud"><div class="score">${h} ${this.match.score.home} | ${a} ${this.match.score.away}</div><div>${ordinal(this.match.down)} &amp; ${this.match.toGo} | Ball on ${displayYardLine(this.match)}</div><div>Play: ${this.currentPlay?.name || 'Pick a play'} | Target: ${this.target}</div><div>${this.status}</div></div><div class="controls">WASD move | Shift sprint | Space snap/juke | 1-4 throw/select | Esc pause</div>`; if (this.phase === 'play-select' && this.match.possession === 'home') html += `<section class="play-select">${PLAYS.map((p,i)=>`<button class="play-card ${i===this.playIndex?'selected':''}" data-play="${p.id}"><span>${p.type.toUpperCase()}</span><strong>${p.name}</strong><small>${p.description}</small></button>`).join('')}</section>`; this.uiRoot.innerHTML = html; }
  showResults() { this.uiRoot.innerHTML = `<section class="screen compact-screen"><h2>${this.match.winner} Wins</h2><p>${this.match.homeTeam.shortName} ${this.match.score.home} | ${this.match.awayTeam.shortName} ${this.match.score.away}</p><div class="stat-grid"><span>Home TD ${this.match.stats.home.touchdowns}</span><span>Away TD ${this.match.stats.away.touchdowns}</span><span>Home Pass ${this.match.stats.home.passingYards}</span><span>Away Pass ${this.match.stats.away.passingYards}</span><span>Home Rush ${this.match.stats.home.rushingYards}</span><span>Away Rush ${this.match.stats.away.rushingYards}</span><span>INT ${this.match.stats.home.interceptions + this.match.stats.away.interceptions}</span><span>Tackles ${this.match.stats.home.tackles + this.match.stats.away.tackles}</span></div><button data-action="rematch">Rematch</button><button data-action="main-menu">Main Menu</button></section>`; }
  ensureAudio() { if (!this.audio) this.audio = new AudioContext(); }
  sound(name) { if (!this.audio) return; const map = { select:420, snap:180, throw:620, catch:760, tackle:82, touchdown:330, turnover:120 }; const o = this.audio.createOscillator(), g = this.audio.createGain(); o.type = 'square'; o.frequency.value = map[name] || 300; g.gain.value = .06; g.gain.exponentialRampToValueAtTime(.001, this.audio.currentTime + .16); o.connect(g).connect(this.audio.destination); o.start(); o.stop(this.audio.currentTime + .17); }
  toast(m) { this.toastRoot.textContent = m; this.toastRoot.classList.add('show'); setTimeout(() => this.toastRoot.classList.remove('show'), 1800); }
  loop() { requestAnimationFrame(() => this.loop()); const now = performance.now(); const dt = Math.min(.04,(now-this.last)/1000); this.last = now; this.elapsed += dt; this.update(dt,this.elapsed); this.renderer.render(this.scene,this.camera); }
}
function teamCard(t, sel, cpu) { return `<button class="team-card ${sel?'selected':''}" data-team="${t.id}" data-cpu="${cpu?'1':'0'}"><span class="logo" style="background:${t.colors.primary};color:${t.colors.accent}">${t.logo}</span><strong>${t.name}</strong><small>${t.identity}</small><span>SPD ${t.stats.speed} / POW ${t.stats.power} / PAS ${t.stats.passing} / DEF ${t.stats.defense}</span></button>`; }
function mat(c) { return new THREE.MeshLambertMaterial({ color:c, flatShading:true, fog:true }); }
function box(x,y,z,c) { return new THREE.Mesh(new THREE.BoxGeometry(x,y,z), mat(c)); }
function playerMesh(team, jersey) { const g = new THREE.Group(); const parts = [[1.1,1.5,.7,0,2.3,0,jersey],[1.55,.45,.8,0,2.95,0,jersey],[.42,1.1,.42,-.35,1,0,team.colors.pants],[.42,1.1,.42,.35,1,0,team.colors.pants],[.56,.22,.75,-.35,.3,.04,'#111'],[.56,.22,.75,.35,.3,.04,'#111']]; parts.forEach(p => { const m = box(p[0],p[1],p[2],p[6]); m.position.set(p[3],p[4],p[5]); g.add(m); }); const h = new THREE.Mesh(new THREE.SphereGeometry(.54,8,6), mat(team.colors.accent)); h.scale.z=.82; h.position.y=3.75; g.add(h); return g; }
function moveToward(p, target, speed, dt) { if (!target) return; const pos = p.mesh.position; const dx = target.x - pos.x, dz = target.z - pos.z, d = Math.hypot(dx,dz); if (d < .4) { p.routeIndex = Math.min((p.routeIndex||0)+1, (p.route?.length||1)-1); return; } pos.x += dx/d*speed*dt; pos.z += dz/d*speed*dt; p.mesh.rotation.y = Math.atan2(dx,dz); }
function clamp(v,a,b) { return Math.max(a, Math.min(b, v)); }
function loadSettings() { try { return { ...SETTINGS_DEFAULTS, ...JSON.parse(localStorage.getItem('gridiron-blitz-97-save') || '{}').settings }; } catch { return { ...SETTINGS_DEFAULTS }; } }
